#!/bin/sh 
# Use: ./Linker.sh <ADDR> <PREFIX>

BOOT_ADDR="$1"
PREFIX="$2"

if [ -z "$BOOT_ADDR" ] || [ -z "$PREFIX" ]; then
    echo "Use: $0 <BOOT_ADDR> <PREFIX>"
    exit 1
fi

cat <<EOL
PHDRS {
	/*READ | WRITE | EXECUTE*/
	r PT_LOAD FLAGS(4);
	re PT_LOAD FLAGS(5);
	rw PT_LOAD FLAGS(6);
} 
SECTIONS
{
    . = $BOOT_ADDR;

    __${PREFIX}_boot_start__ = .;
    .boot : { KEEP(*(.boot)) } : r
    __${PREFIX}_boot_end__ = .;
    __${PREFIX}_boot_size__ = __${PREFIX}_boot_end__ - __${PREFIX}_boot_start__;

    __${PREFIX}_text_start__ = .;
    .text : { *(.text .text.*) } : re
    __${PREFIX}_text_end__ = .;
    __${PREFIX}_text_size__ = __${PREFIX}_text_end__ - __${PREFIX}_text_start__;

    __${PREFIX}_rodata_start__ = .;
    .rodata : { *(.rodata .rodata.*) } : r
    __${PREFIX}_rodata_end__ = .;
    __${PREFIX}_rodata_size__ = __${PREFIX}_rodata_end__ - __${PREFIX}_rodata_start__;

    __${PREFIX}_data_start__ = .;
    .data : { *(.data .data.* .sdata .sdata.*) } : rw
    __${PREFIX}_data_end__ = .;
    __${PREFIX}_data_size__ = __${PREFIX}_data_end__ - __${PREFIX}_data_start__;

    __${PREFIX}_bss_start__ = .;
    .bss : { *(.bss .bss.* .sbss .sbss.* COMMON) } :rw
    __${PREFIX}_bss_end__ = .;
    __${PREFIX}_bss_size__ = __${PREFIX}_bss_end__ - __${PREFIX}_bss_start__;

    __${PREFIX}_START__ = __${PREFIX}_boot_start__;
    __${PREFIX}_END__   = __${PREFIX}_bss_end__;
}
EOL
