#!/bin/sh
# Use: ./Linker.sh <ADDR> <PREFIX> [PAGE_SIZE]

PA="$1"
PREFIX="$2"
PAGE_SIZE="$3"

if [ -z "$PA" ] || [ -z "$PREFIX" ]; then
    echo "Use: $0 <PA> <PREFIX> [PAGE_SIZE]"
    exit 1
fi

if [ -n "$PAGE_SIZE" ]; then
    ALIGNMENT=". = ALIGN($PAGE_SIZE);"
else
    ALIGNMENT=""
fi

cat <<EOL
PHDRS {
    /*READ | WRITE | EXECUTE*/
    r PT_LOAD FLAGS(4);
    re PT_LOAD FLAGS(5);
    rw PT_LOAD FLAGS(6);
}
SECTIONS
{
    . = $PA;

    __${PREFIX}_text_start__ = .;
    .boot : { KEEP(*(.boot)) } : re
    .text : { *(.text .text.*) } : re
    $ALIGNMENT
    __${PREFIX}_text_end__ = .;
    __${PREFIX}_text_size__ = __${PREFIX}_text_end__ - __${PREFIX}_text_start__;

    __${PREFIX}_rodata_start__ = .;
    .rodata : { *(.rodata .rodata.*) } : r
    $ALIGNMENT
    __${PREFIX}_rodata_end__ = .;
    __${PREFIX}_rodata_size__ = __${PREFIX}_rodata_end__ - __${PREFIX}_rodata_start__;


    __${PREFIX}_data_start__ = .;
    .data : { *(.data .data.* .sdata .sdata.*) } : rw
    $ALIGNMENT
    __${PREFIX}_data_end__ = .;
    __${PREFIX}_data_size__ = __${PREFIX}_data_end__ - __${PREFIX}_data_start__;

    __${PREFIX}_bss_start__ = .;
    .bss : { *(.bss .bss.* .sbss .sbss.* COMMON) } :rw
    $ALIGNMENT
    __${PREFIX}_bss_end__ = .;
    __${PREFIX}_bss_size__ = __${PREFIX}_bss_end__ - __${PREFIX}_bss_start__;


    __${PREFIX}_START__ = __${PREFIX}_text_start__;
    __${PREFIX}_END__   = __${PREFIX}_bss_end__;
}
EOL

