#!/bin/sh

get() {
    #FILE="$1"
    VAR="$1"
    INPUT=$(mktemp)
    OUT=$(mktemp)

    cat > "$INPUT" <<EOL
#include <iostream>
#include <Traits.hpp>


int main() {
    std::cout << $VAR;
    return 0;
}
EOL

    g++ -x c++ -I"$(pwd)"/include "$INPUT" -o "$OUT"
    "$OUT"
    rm -f "$INPUT" "$OUT"
}

if declare -f "$1" > /dev/null; then
    "$@"
else
    exit 1
fi


