#!/bin/sh

get() {
    FILE="$1"
    VAR="$2"
    INPUT=$(mktemp /tmp/input.XXXXXX.cpp)
    OUT=$(mktemp /tmp/out.XXXXXX.o)

    cat > "$INPUT" <<EOL
#include <iostream>
#include "$FILE"

//extern "C" const char __KERNEL_START__[];
//extern "C" const char __KERNEL_END__[];

int main() {
    std::cout << $VAR;
    return 0;
}
EOL

    g++ -I"$(pwd)" "$INPUT" -o "$OUT"

    "$OUT"

    rm -f "$INPUT" "$OUT"
}


linker() {
    OUT="$1"
    BOOT_ADDR="$2"

    cat > "$OUT" <<EOL
SECTIONS
{
    . = $BOOT_ADDR;

    __boot_start__ = .;
    .boot : { KEEP(*(.boot)) }
    __boot_end__ = .;
    __boot_size__ = __boot_end__ - __boot_start__;

    __text_start__ = .;
    .text : { *(.text .text.*) }
    __text_end__ = .;
    __text_size__ = __text_end__ - __text_start__;

    __rodata_start__ = .;
    .rodata : { *(.rodata .rodata.*) }
    __rodata_end__ = .;
    __rodata_size__ = __rodata_end__ - __rodata_start__;

    __data_start__ = .;
    .data : { *(.data .data.* .sdata .sdata.*) }
    __data_end__ = .;
    __data_size__ = __data_end__ - __data_start__;

    __bss_start__ = .;
    .bss : { *(.bss .bss.* .sbss .sbss.* COMMON) }
    __bss_end__ = .;
    __bss_size__ = __bss_end__ - __bss_start__;

    PROVIDE(__KERNEL_START__ = __boot_start__);
    PROVIDE(__KERNEL_END__   = __bss_end__);
}
EOL
}

if declare -f "$1" > /dev/null; then
    "$@"
else
    exit 1
fi


