#!/bin/sh

INCLUDE="$1"
FILE="$2"
VARIABLE="$3"

if [ -z "$FILE" ] || [ -z "$VARIABLE" ]; then
	echo "Use: $0 <FILE.hpp> <VARIABLE>"
    exit 1
fi

BINARY=$(mktemp /tmp/temp.XXXXXX)

g++ -std=c++20 -o "$BINARY" -x c++ -I"$INCLUDE" \
    -DFILE_INCLUDE=\""$FILE"\" \
    -DVARIABLE="$VARIABLE" \
    - <<'EOF'
#include FILE_INCLUDE
#include <iostream>

int main() {
    std::cout << VARIABLE;
    return 0;
}
EOF

"$BINARY"
rm "$BINARY"

