#!/bin/sh

FILE="$1"
VARIABLE="$2"

if [ -z "$FILE" ] || [ -z "$VARIABLE" ]; then
	echo "Use: $0 <FILE.hpp> <VARIABLE>"
    exit 1
fi

BINARY=$(mktemp /tmp/temp.XXXXXX)

g++ -o "$BINARY" -x c++ -I"$(pwd)" \
    -DFILE_INCLUDE=\""$FILE"\" \
    -DVARIABLE="$VARIABLE" \
    - <<'EOF'
#include FILE_INCLUDE
#include <iostream>

int main() {
    std::cout << VARIABLE;
    return 0;
}
EOF

"$BINARY"
rm "$BINARY"

